services:
  - type: web
    name: crmaster
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: ASSEMBLYAI_API_KEY
        sync: false
      - key: NOTION_API_KEY
        sync: false
      - key: NOTION_DATABASE_ID
        sync: false
