export interface TranscriptionProfile {
  id: string;
  label: string;
  description: string;
  words: string[];
}

const POLITIQUE_VILLE_WORDS = [
  "ANRU",
  "NPNRU",
  "QPV",
  "quartier prioritaire",
  "contrat de ville",
  "cohésion sociale",
  "rénovation urbaine",
  "renouvellement urbain",
  "GUSP",
  "gestion urbaine de proximité",
  "EPCI",
  "intercommunalité",
  "PLU",
  "PLUi",
  "aménagement du territoire",
  "opération de renouvellement urbain",
  "convention pluriannuelle",
  "préfecture",
  "sous-préfecture",
  "DDCS",
  "conseil citoyen",
  "maison de quartier",
  "centre social",
  "médiation sociale",
  "insertion professionnelle",
  "atelier santé ville",
  "CLSPD",
  "tranquillité publique",
  "prévention de la délinquance",
  "mixité sociale",
  "requalification urbaine",
  "appel à projets",
  "CGET",
  "ANCT",
  "Caisse des Dépôts",
  "bailleur social",
  "HLM",
  "copropriété dégradée",
  "politique de peuplement",
  "zone franche urbaine",
  "ZFU",
  "éducation prioritaire",
  "REP",
  "délégué du préfet",
  "chef de projet politique de la ville",
  "diagnostic territorial",
  "budget participatif",
  "démocratie participative",
  "CCAS",
  "action sociale",
  "veille sociale",
  "programme de réussite éducative",
  "conseil local de santé mentale",
];

const RHUMATOLOGIE_WORDS = [
  "polyarthrite rhumatoïde",
  "spondylarthrite ankylosante",
  "spondyloarthrite",
  "arthrose",
  "arthrite",
  "ostéoporose",
  "ostéopénie",
  "goutte",
  "chondrocalcinose",
  "lupus érythémateux",
  "syndrome de Raynaud",
  "fibromyalgie",
  "sciatique",
  "lombalgie",
  "cervicalgie",
  "dorsalgie",
  "tendinite",
  "bursite",
  "capsulite",
  "infiltration corticoïde",
  "corticothérapie",
  "biothérapie",
  "méthotrexate",
  "anti-TNF",
  "rituximab",
  "adalimumab",
  "étanercept",
  "IRM",
  "échographie articulaire",
  "densitométrie osseuse",
  "ostéodensitométrie",
  "facteur rhumatoïde",
  "anticorps anti-CCP",
  "vitesse de sédimentation",
  "protéine C réactive",
  "ponction articulaire",
  "arthroscopie",
  "prothèse de hanche",
  "prothèse de genou",
  "syndrome du canal carpien",
  "tunnel carpien",
  "hernie discale",
  "sténose spinale",
  "fasciite plantaire",
  "épine calcanéenne",
  "algodystrophie",
  "syndrome douloureux régional complexe",
  "ankylose",
  "synovite",
  "épanchement articulaire",
  "HLA-B27",
  "uvéite",
  "rhumatisme psoriasique",
  "sacro-iliite",
  "ostéophyte",
  "chondropathie",
  "ménisque",
  "ligament croisé",
];

export const TRANSCRIPTION_PROFILES: TranscriptionProfile[] = [
  {
    id: "none",
    label: "Aucun (vocabulaire générique)",
    description: "Pas de vocabulaire spécifique boosté.",
    words: [],
  },
  {
    id: "politique-ville",
    label: "Administration — Politique de la ville",
    description: "Urbanisme, cohésion sociale, dispositifs territoriaux.",
    words: POLITIQUE_VILLE_WORDS,
  },
  {
    id: "rhumatologie",
    label: "Médecine — Rhumatologie",
    description: "Pathologies, examens et traitements rhumatologiques.",
    words: RHUMATOLOGIE_WORDS,
  },
];

export function getTranscriptionProfile(id: string | undefined): TranscriptionProfile {
  return TRANSCRIPTION_PROFILES.find((p) => p.id === id) ?? TRANSCRIPTION_PROFILES[0];
}
